# Generated by Django 5.2 on 2025-05-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('STOCK_MANAGER', 'Gestionnaire de Stock'), ('EMPLOYEE', 'Employé')], default='EMPLOYEE', max_length=15, verbose_name='Rôle'),
        ),
    ]
