# Generated by Django 3.2.4 on 2025-04-29 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='reference',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
