# Generated by Django 3.2.4 on 2025-04-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20250429_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='quantite_initiale',
            field=models.IntegerField(default=0),
        ),
    ]
