# Generated by Django 3.2.4 on 2025-04-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='quantite_initiale',
            field=models.IntegerField(),
        ),
    ]
