# Generated by Django 3.2.4 on 2025-04-29 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_quantite_initiale'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(choices=[('ELECTRONIQUE', 'Électronique'), ('VETEMENT', 'Vêtement'), ('ALIMENTAIRE', 'Alimentaire'), ('AUTRE', 'Autre')], default='AUTRE', max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='quantite_initiale',
            field=models.PositiveIntegerField(),
        ),
    ]
