# Generated by Django 5.2 on 2025-05-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20250429_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='quantite_initiale',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
