# Generated by Django 5.2 on 2025-06-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_article_quantite_initiale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['nom'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AddField(
            model_name='article',
            name='seuil_alerte',
            field=models.PositiveIntegerField(default=10, verbose_name="Seuil d'alerte"),
        ),
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(choices=[('ELECTRONIQUE', 'Électronique'), ('VETEMENT', 'Vêtement'), ('ALIMENTAIRE', 'Alimentaire'), ('AUTRE', 'Autre')], default='AUTRE', max_length=50, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout"),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='article',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire'),
        ),
        migrations.AlterField(
            model_name='article',
            name='quantite_initiale',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité initiale'),
        ),
        migrations.AlterField(
            model_name='article',
            name='reference',
            field=models.CharField(max_length=100, unique=True, verbose_name='Référence'),
        ),
    ]
