# Generated by Django 5.2 on 2025-05-03 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_livraison',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='fournisseurs.fournisseur'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20),
        ),
    ]
