# Generated by Django 5.2 on 2025-05-03 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('STOCK_MOVEMENT', 'Mouvements de stock'), ('STOCK_STATE', 'État des stocks'), ('STATS', 'Statistiques')], max_length=20)),
                ('date_generated', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.JSONField()),
            ],
        ),
    ]
