# Generated by Django 3.2.4 on 2025-04-29 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20250429_0403'),
        ('stocks', '0002_auto_20250428_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='mouvement_type',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantite',
            field=models.IntegerField(),
        ),
    ]
