# Generated by Django 3.2.4 on 2025-04-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20250429_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='quantite',
            field=models.PositiveIntegerField(),
        ),
    ]
