# Generated by Django 3.2.4 on 2025-04-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_alter_stockmovement_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='remarque',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantite',
            field=models.PositiveIntegerField(),
        ),
    ]
