# Generated by Django 5.2 on 2025-05-03 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_article_quantite_initiale'),
        ('stocks', '0006_auto_20250429_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='articles.article'),
        ),
    ]
