# Generated by Django 5.2 on 2025-06-20 16:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_article_options_article_seuil_alerte_and_more'),
        ('stocks', '0007_alter_stockmovement_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-date_mouvement'], 'verbose_name': 'Mouvement de stock', 'verbose_name_plural': 'Mouvements de stock'},
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='articles.article', verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='date_mouvement',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du mouvement'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='mouvement_type',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10, verbose_name='Type de mouvement'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantite',
            field=models.PositiveIntegerField(verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='remarque',
            field=models.TextField(blank=True, null=True, verbose_name='Remarque'),
        ),
    ]
